name: Conventional Commits PR title checker

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - edited
      - reopened

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Validate PR's title
        uses: thehanimo/pr-title-checker@v1.3.7
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          pass_on_octokit_error: false
          configuration_path: ".github/pr-title-checker-configuration.json"
